#!/bin/sh

/config/installer/v2rayplug_installer.sh &
/config/installer/kcptun_installer.sh &
/config/installer/goquiet-installer.sh &
/config/installer/ss_libev_installer.sh &
exec /config/installer/cloak-installer.sh



