#!/bin/bash

#Certificate information
KEY_SIZE=2048


#Client remote
IP=127.0.0.1
PORT=1194

TYPE=client

if [ $# -lt 2 ]; then
	echo "Use: ./vpnconf <key_name> --client/--server"
	exit 1
fi


if [ $2 = "--client" ]; then
	TYPE=client
elif [ $2 = "--server" ]; then
	TYPE=server
else
	echo "missing type --client/--server"
	exit 1
fi

if [ -d $1 ]; then
	echo "Certificate already exists"
	exit 1
fi

if [ ! -d ca ]; then
	echo "====CREATING CERTIFICATE AUTHORITY===="

	mkdir ca
	openssl genrsa -out ca/ca.key $KEY_SIZE
	openssl req -new -x509 -key ca/ca.key -out ca/ca.crt -subj "/C=$CRT_COUNTY/ST=$CRT_STATE/L=$CRT_LOCATION/O=$CRT_ORGANISATION/OU=$CRT_ISSUER_CN/CN=CA"
fi

echo "====CREATING CERTIFICATE FOR $1===="

mkdir $1

openssl genrsa -out $1/$1.key $KEY_SIZE
openssl req -new -key $1/$1.key -out $1/$1.csr -subj "/C=$CRT_COUNTY/ST=$CRT_STATE/L=$CRT_LOCATION/O=$CRT_ORGANISATION/OU=$CRT_ISSUER_CN/CN=$1"

openssl x509 -req -in $1/$1.csr -CA ca/ca.crt -CAkey ca/ca.key -CAcreateserial -out $1/$1.crt

if [ $TYPE = "server" ]; then
	openssl dhparam -out $1/dh2048.pem 2048
fi

if [ $TYPE = "client" -a -f client.conf ] || [ $TYPE = "server" -a -f server.conf ] ; then
	echo "====CREATING OVPN FILE FOR $1===="

	OFILE=$1/$1.ovpn
	
	cat $TYPE.conf > $OFILE

	sed -i "s/^remote .*/remote $IP $PORT/" $OFILE >> $OFILE

	sed -i 's/^ca .*/ca [inline]/' $OFILE >> $OFILE
	sed -i 's/^cert .*/cert [inline]/' $OFILE >> $OFILE
	sed -i 's/^key .*/key [inline]/' $OFILE >> $OFILE

	echo "<ca>" >> $OFILE
	cat ca/ca.crt >> $OFILE
	echo "</ca>" >> $OFILE

	echo "<cert>" >> $OFILE
	cat $1/$1.crt >> $OFILE
	echo "</cert>" >> $OFILE

	echo "<key>" >> $OFILE
	cat $1/$1.key >> $OFILE
	echo "</key>" >> $OFILE
else
	echo "$type.conf file not found, if you want to generate an .ovpn file please put your conf in the project directory"
fi

echo "====CONFIGURATION ENDED===="
